version: "3"
services:
  togo-subgraph-main-postgres:
    image: postgres:12.10
    network_mode: bridge
    container_name: togo-subgraph-main-postgres
    volumes:
      - togo-subgraph-main-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  togo-subgraph-main-app:
    image: subgraph-app:latest
    network_mode: bridge
    container_name: togo-subgraph-main-app
    build: .
    env_file:
      - .env
    expose:
      - 8881
    ports:
      - 8881:8881
    depends_on:
      - togo-subgraph-main-postgres
    links:
      - togo-subgraph-main-postgres

volumes:
  togo-subgraph-main-data:
