version: "3"
services:
  togo-subgraph-main-postgres:
    image: postgres:12.10
    network_mode: bridge
    container_name: togo-subgraph-main-postgres
    volumes:
      - togo-subgraph-main-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  togo-subgraph-main-data:
