version: 2.1
orbs: 
  snyk: snyk/snyk@1.2.3

jobs:
  dagger-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.14"
      - run:
          name: "Install Dagger"
          command: |
            cd /usr/local
            wget -O - https://dl.dagger.io/dagger/install.sh | sudo sh
            cd -
      - run:
          name: "Run Dagger Build"
          command: |
            dagger project update
            dagger do build --log-format plain

  dagger-sonarqube:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.14"
      - run:
          name: "Install Dagger"
          command: |
            cd /usr/local
            wget -O - https://dl.dagger.io/dagger/install.sh | sudo sh
            cd -
      - run:
          name: "Run Dagger Static Check"
          command: |
            dagger project update
            dagger do staticAnalysis sonarscanner --log-format plain

  dagger-golangci:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.14"
      - run:
          name: "Install Dagger"
          command: |
            cd /usr/local
            wget -O - https://dl.dagger.io/dagger/install.sh | sudo sh
            cd -
      - run:
          name: "Run Dagger Static Check"
          command: |
            dagger project update
            dagger do staticAnalysis lint --log-format plain

  #synk-scan:
    #docker:
      #- image: cimg/node:lts
    #steps:
      #- checkout
      #- run: npm i
      #- snyk/scan

workflows:
  dagger-workflow:
    jobs:
      - dagger-build
      - dagger-sonarqube
      - dagger-golangci
      #- synk-scan
