// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DogSearch struct {
	Age             []string `json:"age"`
	CareAndBehavior []string `json:"careAndBehavior"`
	CoatLength      []string `json:"coatLength"`
	Distance        int      `json:"distance"`
	Gender          []string `json:"gender"`
	GoodWith        []string `json:"goodWith"`
	Size            []string `json:"size"`
}

type NewImage struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
	Type   string `json:"type"`
}

type NewProfile struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Session struct {
	Jwt string `json:"jwt"`
}
