// Code generated by ent, DO NOT EDIT.

package dogprofilebreed

const (
	// Label holds the string label denoting the dogprofilebreed type in the database.
	Label = "dog_profile_breed"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the dogprofilebreed in the database.
	Table = "dog_profile_breeds"
)

// Columns holds all SQL columns for dogprofilebreed fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
