// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/dog"
)

// Dog is the model entity for the Dog schema.
type Dog struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dog) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case dog.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Dog", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dog fields.
func (d *Dog) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Dog.
// Note that you need to call Dog.Unwrap() before calling this method if this Dog
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dog) Update() *DogUpdateOne {
	return (&DogClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Dog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Dog) Unwrap() *Dog {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dog is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dog) String() string {
	var builder strings.Builder
	builder.WriteString("Dog(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Dogs is a parsable slice of Dog.
type Dogs []*Dog

func (d Dogs) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
