// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/dogprofileowner"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/predicate"
)

// DogProfileOwnerUpdate is the builder for updating DogProfileOwner entities.
type DogProfileOwnerUpdate struct {
	config
	hooks    []Hook
	mutation *DogProfileOwnerMutation
}

// Where appends a list predicates to the DogProfileOwnerUpdate builder.
func (dpou *DogProfileOwnerUpdate) Where(ps ...predicate.DogProfileOwner) *DogProfileOwnerUpdate {
	dpou.mutation.Where(ps...)
	return dpou
}

// Mutation returns the DogProfileOwnerMutation object of the builder.
func (dpou *DogProfileOwnerUpdate) Mutation() *DogProfileOwnerMutation {
	return dpou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dpou *DogProfileOwnerUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dpou.hooks) == 0 {
		affected, err = dpou.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DogProfileOwnerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dpou.mutation = mutation
			affected, err = dpou.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dpou.hooks) - 1; i >= 0; i-- {
			if dpou.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dpou.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dpou.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (dpou *DogProfileOwnerUpdate) SaveX(ctx context.Context) int {
	affected, err := dpou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dpou *DogProfileOwnerUpdate) Exec(ctx context.Context) error {
	_, err := dpou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dpou *DogProfileOwnerUpdate) ExecX(ctx context.Context) {
	if err := dpou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dpou *DogProfileOwnerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dogprofileowner.Table,
			Columns: dogprofileowner.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dogprofileowner.FieldID,
			},
		},
	}
	if ps := dpou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dpou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dogprofileowner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// DogProfileOwnerUpdateOne is the builder for updating a single DogProfileOwner entity.
type DogProfileOwnerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DogProfileOwnerMutation
}

// Mutation returns the DogProfileOwnerMutation object of the builder.
func (dpouo *DogProfileOwnerUpdateOne) Mutation() *DogProfileOwnerMutation {
	return dpouo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dpouo *DogProfileOwnerUpdateOne) Select(field string, fields ...string) *DogProfileOwnerUpdateOne {
	dpouo.fields = append([]string{field}, fields...)
	return dpouo
}

// Save executes the query and returns the updated DogProfileOwner entity.
func (dpouo *DogProfileOwnerUpdateOne) Save(ctx context.Context) (*DogProfileOwner, error) {
	var (
		err  error
		node *DogProfileOwner
	)
	if len(dpouo.hooks) == 0 {
		node, err = dpouo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DogProfileOwnerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dpouo.mutation = mutation
			node, err = dpouo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dpouo.hooks) - 1; i >= 0; i-- {
			if dpouo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dpouo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, dpouo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*DogProfileOwner)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DogProfileOwnerMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (dpouo *DogProfileOwnerUpdateOne) SaveX(ctx context.Context) *DogProfileOwner {
	node, err := dpouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dpouo *DogProfileOwnerUpdateOne) Exec(ctx context.Context) error {
	_, err := dpouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dpouo *DogProfileOwnerUpdateOne) ExecX(ctx context.Context) {
	if err := dpouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dpouo *DogProfileOwnerUpdateOne) sqlSave(ctx context.Context) (_node *DogProfileOwner, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dogprofileowner.Table,
			Columns: dogprofileowner.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dogprofileowner.FieldID,
			},
		},
	}
	id, ok := dpouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DogProfileOwner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dpouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dogprofileowner.FieldID)
		for _, f := range fields {
			if !dogprofileowner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dogprofileowner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dpouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &DogProfileOwner{config: dpouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dpouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dogprofileowner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
