// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/dogprofileowner"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/predicate"
	"github.com/google/uuid"
)

// DogProfileOwnerQuery is the builder for querying DogProfileOwner entities.
type DogProfileOwnerQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DogProfileOwner
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*DogProfileOwner) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DogProfileOwnerQuery builder.
func (dpoq *DogProfileOwnerQuery) Where(ps ...predicate.DogProfileOwner) *DogProfileOwnerQuery {
	dpoq.predicates = append(dpoq.predicates, ps...)
	return dpoq
}

// Limit adds a limit step to the query.
func (dpoq *DogProfileOwnerQuery) Limit(limit int) *DogProfileOwnerQuery {
	dpoq.limit = &limit
	return dpoq
}

// Offset adds an offset step to the query.
func (dpoq *DogProfileOwnerQuery) Offset(offset int) *DogProfileOwnerQuery {
	dpoq.offset = &offset
	return dpoq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dpoq *DogProfileOwnerQuery) Unique(unique bool) *DogProfileOwnerQuery {
	dpoq.unique = &unique
	return dpoq
}

// Order adds an order step to the query.
func (dpoq *DogProfileOwnerQuery) Order(o ...OrderFunc) *DogProfileOwnerQuery {
	dpoq.order = append(dpoq.order, o...)
	return dpoq
}

// First returns the first DogProfileOwner entity from the query.
// Returns a *NotFoundError when no DogProfileOwner was found.
func (dpoq *DogProfileOwnerQuery) First(ctx context.Context) (*DogProfileOwner, error) {
	nodes, err := dpoq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dogprofileowner.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) FirstX(ctx context.Context) *DogProfileOwner {
	node, err := dpoq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DogProfileOwner ID from the query.
// Returns a *NotFoundError when no DogProfileOwner ID was found.
func (dpoq *DogProfileOwnerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dpoq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dogprofileowner.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dpoq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DogProfileOwner entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DogProfileOwner entity is found.
// Returns a *NotFoundError when no DogProfileOwner entities are found.
func (dpoq *DogProfileOwnerQuery) Only(ctx context.Context) (*DogProfileOwner, error) {
	nodes, err := dpoq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dogprofileowner.Label}
	default:
		return nil, &NotSingularError{dogprofileowner.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) OnlyX(ctx context.Context) *DogProfileOwner {
	node, err := dpoq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DogProfileOwner ID in the query.
// Returns a *NotSingularError when more than one DogProfileOwner ID is found.
// Returns a *NotFoundError when no entities are found.
func (dpoq *DogProfileOwnerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dpoq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dogprofileowner.Label}
	default:
		err = &NotSingularError{dogprofileowner.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dpoq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DogProfileOwners.
func (dpoq *DogProfileOwnerQuery) All(ctx context.Context) ([]*DogProfileOwner, error) {
	if err := dpoq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dpoq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) AllX(ctx context.Context) []*DogProfileOwner {
	nodes, err := dpoq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DogProfileOwner IDs.
func (dpoq *DogProfileOwnerQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := dpoq.Select(dogprofileowner.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dpoq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dpoq *DogProfileOwnerQuery) Count(ctx context.Context) (int, error) {
	if err := dpoq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dpoq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) CountX(ctx context.Context) int {
	count, err := dpoq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dpoq *DogProfileOwnerQuery) Exist(ctx context.Context) (bool, error) {
	if err := dpoq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dpoq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dpoq *DogProfileOwnerQuery) ExistX(ctx context.Context) bool {
	exist, err := dpoq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DogProfileOwnerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dpoq *DogProfileOwnerQuery) Clone() *DogProfileOwnerQuery {
	if dpoq == nil {
		return nil
	}
	return &DogProfileOwnerQuery{
		config:     dpoq.config,
		limit:      dpoq.limit,
		offset:     dpoq.offset,
		order:      append([]OrderFunc{}, dpoq.order...),
		predicates: append([]predicate.DogProfileOwner{}, dpoq.predicates...),
		// clone intermediate query.
		sql:    dpoq.sql.Clone(),
		path:   dpoq.path,
		unique: dpoq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DogProfileOwner.Query().
//		GroupBy(dogprofileowner.FieldOwnerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dpoq *DogProfileOwnerQuery) GroupBy(field string, fields ...string) *DogProfileOwnerGroupBy {
	grbuild := &DogProfileOwnerGroupBy{config: dpoq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dpoq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dpoq.sqlQuery(ctx), nil
	}
	grbuild.label = dogprofileowner.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//	}
//
//	client.DogProfileOwner.Query().
//		Select(dogprofileowner.FieldOwnerID).
//		Scan(ctx, &v)
func (dpoq *DogProfileOwnerQuery) Select(fields ...string) *DogProfileOwnerSelect {
	dpoq.fields = append(dpoq.fields, fields...)
	selbuild := &DogProfileOwnerSelect{DogProfileOwnerQuery: dpoq}
	selbuild.label = dogprofileowner.Label
	selbuild.flds, selbuild.scan = &dpoq.fields, selbuild.Scan
	return selbuild
}

func (dpoq *DogProfileOwnerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dpoq.fields {
		if !dogprofileowner.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dpoq.path != nil {
		prev, err := dpoq.path(ctx)
		if err != nil {
			return err
		}
		dpoq.sql = prev
	}
	return nil
}

func (dpoq *DogProfileOwnerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DogProfileOwner, error) {
	var (
		nodes = []*DogProfileOwner{}
		_spec = dpoq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*DogProfileOwner).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &DogProfileOwner{config: dpoq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(dpoq.modifiers) > 0 {
		_spec.Modifiers = dpoq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dpoq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range dpoq.loadTotal {
		if err := dpoq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dpoq *DogProfileOwnerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dpoq.querySpec()
	if len(dpoq.modifiers) > 0 {
		_spec.Modifiers = dpoq.modifiers
	}
	_spec.Node.Columns = dpoq.fields
	if len(dpoq.fields) > 0 {
		_spec.Unique = dpoq.unique != nil && *dpoq.unique
	}
	return sqlgraph.CountNodes(ctx, dpoq.driver, _spec)
}

func (dpoq *DogProfileOwnerQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dpoq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dpoq *DogProfileOwnerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dogprofileowner.Table,
			Columns: dogprofileowner.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: dogprofileowner.FieldID,
			},
		},
		From:   dpoq.sql,
		Unique: true,
	}
	if unique := dpoq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dpoq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dogprofileowner.FieldID)
		for i := range fields {
			if fields[i] != dogprofileowner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dpoq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dpoq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dpoq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dpoq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dpoq *DogProfileOwnerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dpoq.driver.Dialect())
	t1 := builder.Table(dogprofileowner.Table)
	columns := dpoq.fields
	if len(columns) == 0 {
		columns = dogprofileowner.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dpoq.sql != nil {
		selector = dpoq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dpoq.unique != nil && *dpoq.unique {
		selector.Distinct()
	}
	for _, p := range dpoq.predicates {
		p(selector)
	}
	for _, p := range dpoq.order {
		p(selector)
	}
	if offset := dpoq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dpoq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DogProfileOwnerGroupBy is the group-by builder for DogProfileOwner entities.
type DogProfileOwnerGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dpogb *DogProfileOwnerGroupBy) Aggregate(fns ...AggregateFunc) *DogProfileOwnerGroupBy {
	dpogb.fns = append(dpogb.fns, fns...)
	return dpogb
}

// Scan applies the group-by query and scans the result into the given value.
func (dpogb *DogProfileOwnerGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dpogb.path(ctx)
	if err != nil {
		return err
	}
	dpogb.sql = query
	return dpogb.sqlScan(ctx, v)
}

func (dpogb *DogProfileOwnerGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dpogb.fields {
		if !dogprofileowner.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dpogb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dpogb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dpogb *DogProfileOwnerGroupBy) sqlQuery() *sql.Selector {
	selector := dpogb.sql.Select()
	aggregation := make([]string, 0, len(dpogb.fns))
	for _, fn := range dpogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dpogb.fields)+len(dpogb.fns))
		for _, f := range dpogb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dpogb.fields...)...)
}

// DogProfileOwnerSelect is the builder for selecting fields of DogProfileOwner entities.
type DogProfileOwnerSelect struct {
	*DogProfileOwnerQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dpos *DogProfileOwnerSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dpos.prepareQuery(ctx); err != nil {
		return err
	}
	dpos.sql = dpos.DogProfileOwnerQuery.sqlQuery(ctx)
	return dpos.sqlScan(ctx, v)
}

func (dpos *DogProfileOwnerSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dpos.sql.Query()
	if err := dpos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
