// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/OSBC-LLC/togo-subgraph-main/ent/dogprofileowner"
)

// DogProfileOwner is the model entity for the DogProfileOwner schema.
type DogProfileOwner struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DogProfileOwner) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case dogprofileowner.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type DogProfileOwner", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DogProfileOwner fields.
func (dpo *DogProfileOwner) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dogprofileowner.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dpo.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this DogProfileOwner.
// Note that you need to call DogProfileOwner.Unwrap() before calling this method if this DogProfileOwner
// was returned from a transaction, and the transaction was committed or rolled back.
func (dpo *DogProfileOwner) Update() *DogProfileOwnerUpdateOne {
	return (&DogProfileOwnerClient{config: dpo.config}).UpdateOne(dpo)
}

// Unwrap unwraps the DogProfileOwner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dpo *DogProfileOwner) Unwrap() *DogProfileOwner {
	_tx, ok := dpo.config.driver.(*txDriver)
	if !ok {
		panic("ent: DogProfileOwner is not a transactional entity")
	}
	dpo.config.driver = _tx.drv
	return dpo
}

// String implements the fmt.Stringer.
func (dpo *DogProfileOwner) String() string {
	var builder strings.Builder
	builder.WriteString("DogProfileOwner(")
	builder.WriteString(fmt.Sprintf("id=%v", dpo.ID))
	builder.WriteByte(')')
	return builder.String()
}

// DogProfileOwners is a parsable slice of DogProfileOwner.
type DogProfileOwners []*DogProfileOwner

func (dpo DogProfileOwners) config(cfg config) {
	for _i := range dpo {
		dpo[_i].config = cfg
	}
}
